### PR TITLE
Port documentation from Wiki: Binary field #323

### PR DESCRIPTION
**Pull request by HeroicHitesh**
Check if it solves issue #323 and suggest if something else needs to be done.

### CODE REVIEW

**Comment by herflis** [comment]
Hey @HeroicHitesh ,
you should also copy the content of this article 👉 http://wiki.sensenet.com/Binary_Field 🙂

**Comment by HeroicHitesh** [comment]
I saw the article it's same only the links are different. So, do we need to change update the links to point to the `.md` files

**Review by HeroicHitesh — COMMENTED** [review]
In line 43 do we need to change `Example` to `Example/Tutorials` or leave it as it is. There are some more lines where such tiny changes are present.

**Comment by HeroicHitesh** [comment]
@herflis please review the file and suggest necessary changes.

**Pull request merged**
