### PR TITLE
Concatenate using ES6 template literals

### PR DESCRIPTION
**Pull request by mrassili**

### CODE REVIEW

**Comment by zoltanbedi** [comment]
Hey @mrassili , thank you for your contribution, but we feel that is not fair to other participants to accept this type of pull requests, so we'll mark it as 'invalid'. We would be happy to reward you with some extra swag, so please don't give up, create another pr with quality changes! Keep up the good work! 💙

**Comment by mrassili** [comment]
Hey @B3zo0 I thought you said 
> Any contributions are welcome no contribution is too small.

you're gonna have to switch from `+` concatenation at some point anyway
Thanks

**Comment by zoltanbedi** [comment]
Hey @mrassili, I understand that you might feel offended because we closed your pr. Thing is that your contribution has no value for us. If we would want to see our js in es6 we would created an issue for it. In the near future we will rewrite this site anyway.

**Comment by mrassili** [comment]
I understand. No worries

**Pull request closed without merging**
