### PR TITLE
Removed obsolete sn-webpages links

### PR DESCRIPTION
**Pull request by codetronaut**
Removed obsolete sn-webpages links from the "starting out with MVC" doc

### CODE REVIEW

**Comment by codetronaut** [comment]
@B3zo0 and @herflis please review this pull request.
And please let me know how can I improve it.

**Comment by zoltanbedi** [comment]
Hi @codetronaut thanks for your help. Did you have a chance to try it out? We want to make sure that you can complete the tutorial without the sn-webpages package.

**Comment by codetronaut** [comment]
@B3zo0 No I haven't tried it yet.

**Comment by herflis** [comment]
Hey @codetronaut , as it is stated in the referenced issue, the tutorial has to be reviewed as well, to check that is is working without the sn-webpages installation.

**Pull request closed without merging**
