### PR TITLE
Update 2016-08-26-permission-overview-tool-making-sense-of-your-permi…

### PR DESCRIPTION
**Pull request by V0lk3n**
At the end of line 8 you forgot a " . "

### CODE REVIEW

**Comment by herflis** [comment]
Hey @V0lk3n ,
it's a nice catch, thank you! Can you please add some more fixes to this pr? We really appreciate every little bit of help, but it will be not fair to other contributors who are doing serious work to accept these kind of pr's.

**Comment by V0lk3n** [comment]
Give me few time and i will check it :)

**Comment by V0lk3n** [comment]
What did you try to mean by "but that dit not give administrators the full picture."? What is for you "the full picture"

**Comment by V0lk3n** [comment]
Nice answer...

**Pull request closed without merging**
