### PR TITLE
[Post] Internal knowledge sharing - is it the base of the brain?

### PR DESCRIPTION
**Pull request by borsi**
Aand another one of Balázs's business-themed post. This one's for a bit later.
Please review the 
- [ ] Content
- [ ] Style, and
- [ ] Grammar.

@balazskeszei - pls add or send images to this post. A splash image for the post collection page is a minimum, but I think I'd be okay with some images mid-text as well. 🌮

### CODE REVIEW

**Review by herflis — COMMENTED** [review]
1. @balazskeszei pls upload the pictures to the posts/internal-knowledge-sharing branch, because we cannot review the posts draft version with pictures
2. The first image (with the head) doesn't fit the style of the others

**Comment by herflis** [comment]
@balazskeszei pls add 2-3 sentences as a lead/description at the top of the post to display it on the blog main page

The lead image does not fit the style of the blog lead images and it has a wrong aspect

**Comment by herflis** [comment]
@balazskeszei pls add 2-3 sentences as a lead/description at the top of the post to display it on the blog main page

**Review by balazskeszei — APPROVED** [review]

**Comment by herflis** [comment]
I've made some improvements on the images in the post and because of these changes i had to merge master into this branch, sorry :) 
Btw the lead text is still missing

**Review by herflis — APPROVED** [review]

**Review by tusmester — APPROVED** [review]

**Pull request merged**
