### PR TITLE
Edit Facebook links for sense/net CMS

### LINKED ISSUE #379: Facebook Page Moved? Edit Facebook links
It appears that the Sense/Net Facebook page is closed or otherwise deleted. Thus, links to the SenseNet Facebook page on this website all 404 and should be removed.

### PR DESCRIPTION
**Pull request by crweiner**
Closes #379 

It appears that the Sense/Net Facebook group/page is closed, so this PR removes the dead links to the Facebook page across the entire site. :+1: :smile:  :blue_book:

### CODE REVIEW

**Comment by herflis** [comment]
Hey @crweiner ,
thank for your help! The fb page is not closed, it was just renamed by somebody, who didn't think that it would be a problem. 😅 So the links should be changed to [https://www.facebook.com/sensenetcsp](https://www.facebook.com/sensenetcsp), it would be nice if you could do it 😊

**Comment by crweiner** [comment]
Hi @herflis!

Thanks for letting me know! I've reverted the deletion commit and changed the links to point to https://www.facebook.com/sensenetcsp. Let me know if you need anything else! :+1: Happy Hacktoberfest! :jack_o_lantern:

**Comment by herflis** [comment]
@crweiner awesome, thanks! 💙 Don't forget to register 👉 [here](https://sensenet.com/Hacktoberfest2019) for the extra swag!

**Comment by crweiner** [comment]
Submitted the form, thank you! :smiley: :fireworks:

**Pull request merged**
