### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HeroicHitesh**
README.md file is updated to mention CONTRIBUTING.md file.

### CODE REVIEW

**Comment by HeroicHitesh** [comment]
issue #4 is solved with this update.

**Comment by herflis** [comment]
Hey @HeroicHitesh  , thank you for your contribution, but we feel that is not fair to other participants to accept this type of pull requests, so we'll mark it as 'invalid'. We would be happy to reward you with some extra swag, so please don't give up, create another pr with quality changes! Keep up the good work! 💙

**Comment by HeroicHitesh** [comment]
Hi @herflis , Is it necessary to create PRs for issues with label "hacktoberfest" or can we do for any issue. As there is no hacktoberfest issue left unassigned.

**Comment by herflis** [comment]
Hi @HeroicHitesh 
I've just added a bunch of issues with the 'hacktoberfest' label, check if there's something for you 🙂
👉 [here](https://github.com/SenseNet/sensenet.github.io/labels/hacktoberfest)

**Pull request closed without merging**
